package cn.sh.outer.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USER_ACCOUNT
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PASSWORD
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.NAME
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.AGE
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.STATUS
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.CREATE_TIME
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.UPDATE_TIME
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PHONE_NUMBER
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.GENDER
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.EMAIL
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.ADDRESS
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.ID
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    private String id;

    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.USER_ACCOUNT
     *
     * @param userAccount the value for T_USER.USER_ACCOUNT
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PASSWORD
     *
     * @return the value of T_USER.PASSWORD
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.PASSWORD
     *
     * @param password the value for T_USER.PASSWORD
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.NAME
     *
     * @return the value of T_USER.NAME
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.NAME
     *
     * @param name the value for T_USER.NAME
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.AGE
     *
     * @return the value of T_USER.AGE
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.AGE
     *
     * @param age the value for T_USER.AGE
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.STATUS
     *
     * @return the value of T_USER.STATUS
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.STATUS
     *
     * @param status the value for T_USER.STATUS
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.CREATE_TIME
     *
     * @return the value of T_USER.CREATE_TIME
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.CREATE_TIME
     *
     * @param createTime the value for T_USER.CREATE_TIME
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.UPDATE_TIME
     *
     * @return the value of T_USER.UPDATE_TIME
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.UPDATE_TIME
     *
     * @param updateTime the value for T_USER.UPDATE_TIME
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PHONE_NUMBER
     *
     * @return the value of T_USER.PHONE_NUMBER
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.PHONE_NUMBER
     *
     * @param phoneNumber the value for T_USER.PHONE_NUMBER
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.GENDER
     *
     * @return the value of T_USER.GENDER
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.GENDER
     *
     * @param gender the value for T_USER.GENDER
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.EMAIL
     *
     * @return the value of T_USER.EMAIL
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.EMAIL
     *
     * @param email the value for T_USER.EMAIL
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.ADDRESS
     *
     * @return the value of T_USER.ADDRESS
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.ADDRESS
     *
     * @param address the value for T_USER.ADDRESS
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.ID
     *
     * @return the value of T_USER.ID
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.ID
     *
     * @param id the value for T_USER.ID
     *
     * @mbggenerated Wed Jun 17 14:09:04 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }


    
	
}