package cn.sh.outer.dao;

import cn.sh.ideal.manager.model.UserRole;

import java.math.BigDecimal;
import java.util.List;

public interface UserRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated Wed Jun 17 16:04:30 CST 2015
     */
	int deleteByPrimaryKey(BigDecimal id);
	
	
    int deleteByUserId(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated Wed Jun 17 16:04:30 CST 2015
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated Wed Jun 17 16:04:30 CST 2015
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated Wed Jun 17 16:04:30 CST 2015
     */
    UserRole selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated Wed Jun 17 16:04:30 CST 2015
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated Wed Jun 17 16:04:30 CST 2015
     */
    int updateByPrimaryKey(UserRole record);


	List<UserRole> query(UserRole userRole);
}