package cn.sh.outer.dao;

import cn.sh.outer.model.User;

import java.math.BigDecimal;
import java.util.List;

public interface UserDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER
	 * @mbggenerated  Wed Jun 17 14:30:37 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER
	 * @mbggenerated  Wed Jun 17 14:30:37 CST 2015
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER
	 * @mbggenerated  Wed Jun 17 14:30:37 CST 2015
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER
	 * @mbggenerated  Wed Jun 17 14:30:37 CST 2015
	 */
	User selectByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER
	 * @mbggenerated  Wed Jun 17 14:30:37 CST 2015
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER
	 * @mbggenerated  Wed Jun 17 14:30:37 CST 2015
	 */
	int updateByPrimaryKey(User record);
	
	
	List<User> query(User user);

	boolean exists(User user);

	void deleteUserRole(User user);
}